name: Run JavaScript Code

on: [push]

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run code
      run: |
        echo "Current directory:"
        pwd
        echo "Directory after changing to js:"
        cd js
        pwd
        node ./4sum.js
